server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/music?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
  cache:
    type: jcache
    jcache:
      config: classpath:ehcache-3.x.xml
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
